
package servicesweb;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MonServiceWeb", targetNamespace = "http://servicesWeb/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MonServiceWeb {


    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ageLylia", targetNamespace = "http://servicesWeb/", className = "servicesweb.AgeLylia")
    @ResponseWrapper(localName = "ageLyliaResponse", targetNamespace = "http://servicesWeb/", className = "servicesweb.AgeLyliaResponse")
    @Action(input = "http://servicesWeb/MonServiceWeb/ageLyliaRequest", output = "http://servicesWeb/MonServiceWeb/ageLyliaResponse")
    public int ageLylia();

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "afficheLylia", targetNamespace = "http://servicesWeb/", className = "servicesweb.AfficheLylia")
    @ResponseWrapper(localName = "afficheLyliaResponse", targetNamespace = "http://servicesWeb/", className = "servicesweb.AfficheLyliaResponse")
    @Action(input = "http://servicesWeb/MonServiceWeb/afficheLyliaRequest", output = "http://servicesWeb/MonServiceWeb/afficheLyliaResponse")
    public void afficheLylia();

}
